### ISSUE TITLE
rezolva works when built from source, but not from pypi

### ISSUE THREAD

**Issue by jose-perales** [joshmeek/start-er#17]
steps to repro:

1. clone repo
2. `uv venv`
3. `uv pip install rezolva`
4. `.venv/bin/python examples/vector_based_example.py` (bug should affect all examples)

results in:

```
Traceback (most recent call last):
  File "/Users/jperales/Documents/dev/rezolva/examples/vector_based_example.py", line 1, in <module>
    from rezolva import Entity, EntityResolver, SimpleBlocker, SimplePreprocessor
  File "/Users/jperales/Documents/dev/rezolva/.venv/lib/python3.12/site-packages/rezolva/__init__.py", line 3, in <module>
    from .blockers.simple_blocker import SimpleBlocker
ModuleNotFoundError: No module named 'rezolva.blockers'
```

however, same steps except where 3 is replaced by `uv pip install -e .` (built from source) gives:

```
Top matches for 5 - iPhone 12 Pro Max:
  Match: 2 - iphone 12 pro (Score: 0.76)

Top matches for 6 - Galaxy S21 Ultra:
  Match: 3 - galaxy s21 (Score: 0.80)


Vector representations:
Entity 1:
  a14: 0.0693
  bionic: 0.0693
  chip: 0.0693
  apple: 0.0575
  iphone: 0.0288

Entity 2:
  pro: 0.0693
  premium: 0.0693
  lidar: 0.0693
  scanner: 0.0693
  apple: 0.0575

Entity 3:
  galaxy: 0.0770
  s21: 0.0770
  samsungs: 0.0770
  flagship: 0.0770
  phone: 0.0770

Entity 4:
  pixel: 0.0770
  5: 0.0770
  googles: 0.0770
  5g: 0.0770
  support: 0.0770
```

which works as expected.

**Comment by jose-perales** [comment]
steps to reproduce creates an `__init__.py`:

<img width="1465" alt="image" src="https://github.com/user-attachments/assets/e7f7c00c-fe1b-43fb-aab7-cdc8ffcf66ec">

whereas building from source gives:

<img width="1624" alt="image" src="https://github.com/user-attachments/assets/9ee51670-dd33-4b65-b4d6-96b642124caa">

**Comment by joshmeek** [comment]
Should be fixed in the 0.2.1 release going out right now 🙂

**Comment by jose-perales** [comment]
still broken - still the same `ModuleNotFoundError`

**Comment by joshmeek** [comment]
Check now w/ version 0.2.2

**Comment by jose-perales** [comment]
works as expected now
